name: Check with ESLint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: yarn

      - name: Run ESLint
        run: yarn lint
